Repository kubernetes-csi/csi-lib-iscsi, pull requests merged in 2020-01, with the labels that each got.

#13 support device with multiple targets
  iscsi/iscsi.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#15 use os.IsNotExist and other small fixes
  iscsi/iscsi.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#17 improve discoverydb method
  iscsi/iscsi.go
  iscsi/iscsiadm.go
  iscsi/iscsiadm_test.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, release-note-none, size/M

#21 Remove Brad Childs from OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
